version: "v3"
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "80:5001"
    volumes:
      - .:/app
#    depends_on:
#      - redis-server
#  redis-server:
#    build:
#      dockerfile: redis.Dockerfile
