name: Lint and unit test
run-name: "${{ github.actor }} is running ${{ github.workflow }} on ${{ github.repository }}"
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "**/*.go"
jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.0

      - name: Check out code
        uses: actions/checkout@v4

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56.2
          skip-go-installation: true
          args: --timeout 3m

      - name: Unit test
        run: make run-test